project:
  type: website
  output-dir: docs

website:
  title: "Home"
  favicon: logo.png
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: research/index.qmd
        text: Research
      - href: cv.pdf
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    comments:
      giscus:
        repo: chengchen2326/chengchen2326.github.io
        repo-id: "955350406"  
        category: "General"
        mapping: pathname
        reactions-enabled: true  
        input-position: bottom
        theme: light

editor:
  render-on-save: true

  

    